global using Blockchain;
global using Blockchain.Areas.Identity;
global using Blockchain.Data;
global using Blockchain.Shared;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;